version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: parking-mongo
    command: ["--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parking-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - FRONTEND_ORIGIN=http://localhost:5173
      - MONGODB_URI=mongodb://mongo:27017/bku-smart-parking
      - MONGODB_DB=bku-smart-parking
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parking-frontend
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
